# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      buildDir: '${{ github.workspace }}/build'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: sudo apt-get install doxygen python3-breathe python3-sphinx
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: run-cmake
        # You may pin to the exact commit or the version.
        # uses: lukka/run-cmake@7ba4481660f0f04c86cfa5f1f24b90effc97bde1
        uses: lukka/run-cmake@v3.4
        with:
          buildWithCMakeArgs: --target doc
          buildDirectory: ${{ env.buildDir }}


      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.buildDir }}/sphinx
